from typing import Protocol, Sequence, Mapping

from src.prompts.schemas import (
    PromptAsset,
    PromptResolveRequest,
    PromptResolveResult,
    PromptInvalidationEvent,
    RefreshReport,
)


class PromptSource(Protocol):
    async def get_asset(self, prompt_key: str, locale: str | None = None) -> PromptAsset: ...
    async def list_assets_version_hash(self) -> Mapping[str, str]: ...


class PromptCache(Protocol):
    async def get(self, key: str) -> PromptResolveResult | None: ...
    async def set(self, key: str, value: PromptResolveResult, ttl_seconds: int) -> None: ...
    async def invalidate_prefix(self, prefix: str) -> int: ...


class PromptInvalidationBus(Protocol):
    async def publish(self, event: PromptInvalidationEvent) -> None: ...
    async def subscribe(self) -> None: ...
    async def recv(self) -> PromptInvalidationEvent | None: ...


class TokenEstimator(Protocol):
    def estimate(self, messages: Sequence[dict], model: str) -> int: ...


class TokenBudgetGuard(Protocol):
    def validate_or_raise(self, *, token_estimate: int, max_input_tokens: int, reserve_output_tokens: int) -> None: ...


class ABRouter(Protocol):
    def choose_variant(self, *, prompt_key: str, bucket_key: str, variants: Sequence[str], variant_hint: str | None = None) -> str: ...


class PromptProvider(Protocol):
    async def resolve(self, req: PromptResolveRequest) -> PromptResolveResult: ...
    async def invalidate(self, event: PromptInvalidationEvent) -> None: ...
    async def refresh(self, prompt_key: str | None = None) -> RefreshReport: ...
